#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# check branches to commit in
branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to the 'main' branch"
  exit 1
fi

if [ "$branch" = "develop" ]; then
  echo "You can't commit directly to the 'develop' branch"
  exit 1
fi

# run linting command
npm run lint

# continue with the commit if everything passed
exit 0
